### ISSUE TITLE
Discord Channel Invitation expired.

### ISSUE THREAD

**Issue by Tiancheng-Luo** [semiosis/pen.el#23]
I'm sorry to notice the invitation `https://discord.gg/6wP4MwCM`  has expired. I've just come across your language model and completion research and I want to know more about it. 
Is it possible for me to have an updated invitation?

**Comment by mullikine** [comment]
Hi  Tiancheng-Luov,
Thank you for noticing thatt. I have updated with a permanent invitation :)

https://discord.gg/6wP4MwCM
