### ISSUE TITLE
semiosis/pen:latest -> semiosis/pen.el:latest

### ISSUE THREAD

**Issue by Gurkenglas** [semiosis/pen.el#33]
This typo (?) in installation.org sent me on quite a goose chase!

**Comment by mullikine** [comment]
Oh wow. Thank you -- So sorry

**Comment by mullikine** [comment]
Hmm. I want both. Perhaps I will use both docker tags from now on. Thank you.

**Comment by Gurkenglas** [comment]
Don't forget https://semiosis.github.io/posts/pen-el-installation-from-scratch/

**Comment by mullikine** [comment]
Done, and done. Thank you very much Sir! I have also taken both docker tags. Ouch, this mustve surely hurt adoption
